export enum WalletId {
  METAMASK = 'METAMASK',
  TRUST = 'TRUST',
  CIPHER = 'CIPHER',
  MIST = 'MIST',
  FRAME = 'FRAME',
  LEDGER_NANO_S = 'LEDGER_NANO_S',
  TREZOR = 'TREZOR',
  SAFE_T_MINI = 'SAFE_T_MINI',
  PARITY_SIGNER = 'PARITY_SIGNER',
  KEYSTORE_FILE = 'KEYSTORE_FILE',
  PRIVATE_KEY = 'PRIVATE_KEY',
  MNEMONIC_PHRASE = 'MNEMONIC_PHRASE',
  VIEW_ONLY = 'VIEW_ONLY'
}
