export enum WalletId {
  WEB3 = 'WEB3',
  METAMASK = 'METAMASK',
  TRUST = 'TRUST',
  FRAME = 'FRAME',
  COINBASE = 'COINBASE',
  LEDGER_NANO_S = 'LEDGER_NANO_S',
  TREZOR = 'TREZOR',
  PARITY_SIGNER = 'PARITY_SIGNER',
  KEYSTORE_FILE = 'KEYSTORE_FILE',
  PRIVATE_KEY = 'PRIVATE_KEY',
  MNEMONIC_PHRASE = 'MNEMONIC_PHRASE',
  VIEW_ONLY = 'VIEW_ONLY',
  WALLETCONNECT = 'WALLETCONNECT'
}
