export enum TypeKeys {
  DATA_FIELD_SET = 'DATA_FIELD_SET',
  GAS_LIMIT_FIELD_SET = 'GAS_LIMIT_FIELD_SET',
  TO_FIELD_SET = 'TO_FIELD_SET',
  VALUE_FIELD_SET = 'VALUE_FIELD_SET',
  NONCE_FIELD_SET = 'NONCE_FIELD_SET',
  UNIT_META_SET = 'UNIT_META_SET',
  DECIMAL_META_SET = 'DECIMAL_META_SET',
  TOKEN_VALUE_META_SET = 'TOKEN_VALUE_META_SET',
  RESET = 'RESET'
}
