export const SWAP_STEP = 'SWAP_STEP';
export const SWAP_ORIGIN_KIND = 'SWAP_ORIGIN_KIND';
export const SWAP_DESTINATION_KIND = 'SWAP_DESTINATION_KIND';
export const SWAP_ORIGIN_AMOUNT = 'SWAP_ORIGIN_AMOUNT';
export const SWAP_DESTINATION_AMOUNT = 'SWAP_DESTINATION_AMOUNT';
export const SWAP_LOAD_BITY_RATES_SUCCEEDED = 'SWAP_LOAD_BITY_RATES_SUCCEEDED';
export const SWAP_DESTINATION_ADDRESS = 'SWAP_DESTINATION_ADDRESS';
export const SWAP_RESTART = 'SWAP_RESTART';
export const SWAP_LOAD_BITY_RATES_REQUESTED = 'SWAP_LOAD_BITY_RATES_REQUESTED';
export const SWAP_STOP_LOAD_BITY_RATES = 'SWAP_STOP_LOAD_BITY_RATES';
export const SWAP_ORDER_TIME = 'SWAP_ORDER_TIME';
export const SWAP_BITY_ORDER_CREATE_SUCCEEDED =
  'SWAP_BITY_ORDER_CREATE_SUCCEEDED';
export const SWAP_ORDER_CREATE_REQUESTED = 'SWAP_ORDER_CREATE_REQUESTED';
export const SWAP_BITY_ORDER_STATUS_SUCCEEDED =
  'SWAP_BITY_ORDER_STATUS_SUCCEEDED';
export const SWAP_BITY_ORDER_STATUS_REQUESTED =
  'SWAP_BITY_ORDER_STATUS_REQUESTED';
export const SWAP_ORDER_START_TIMER = 'SWAP_ORDER_START_TIMER';
export const SWAP_ORDER_STOP_TIMER = 'SWAP_ORDER_STOP_TIMER';
export const SWAP_START_POLL_BITY_ORDER_STATUS =
  'SWAP_START_POLL_BITY_ORDER_STATUS';
export const SWAP_STOP_POLL_BITY_ORDER_STATUS =
  'SWAP_STOP_POLL_BITY_ORDER_STATUS';
