export enum TypeKeys {
  ENS_RESOLVE_DOMAIN_REQUESTED = 'ENS_RESOLVE_DOMAIN_REQUESTED',
  ENS_RESOLVE_DOMAIN_SUCCEEDED = 'ENS_RESOLVE_DOMAIN_SUCCEEDED',
  ENS_RESOLVE_DOMAIN_FAILED = 'ENS_RESOLVE_DOMAIN_FAILED',
  ENS_RESOLVE_DOMAIN_CACHED = 'ENS_RESOLVE_DOMAIN_CACHED',

  ENS_BID_PLACE_REQUESTED = 'ENS_BID_PLACE_REQUESTED',
  ENS_BID_PLACE_SUCCEEDED = 'ENS_BID_PLACE_SUCCEEDED',
  ENS_BID_PLACE_FAILED = 'ENS_BID_PLACE_FAILED',

  BID_MASK_FIELD_SET = 'BID_MASK_FIELD_SET',
  BID_VALUE_FIELD_SET = 'BID_VALUE_FIELD_SET',
  SECRET_FIELD_SET = 'SECRET_FIELD_SET',

  INITIALIZE_INPUTS = 'INITIALIZE_INPUTS',
  BID_MASK_FIELD_INPUT = 'BID_MASK_FIELD_INPUT',
  BID_VALUE_FIELD_INPUT = 'BID_VALUE_FIELD_INPUT',
  SECRET_FIELD_INPUT = 'SECRET_FIELD_INPUT'
}
