export enum TypeKeys {
  ENS_RESOLVE_DOMAIN_REQUESTED = 'ENS_RESOLVE_DOMAIN_REQUESTED',
  ENS_RESOLVE_DOMAIN_SUCCEEDED = 'ENS_RESOLVE_DOMAIN_SUCCEEDED',
  ENS_RESOLVE_DOMAIN_FAILED = 'ENS_RESOLVE_DOMAIN_FAILED',
  ENS_BID_PLACE_REQUESTED = 'ENS_BID_PLACE_REQUESTED',
  ENS_BID_PLACE_SUCCEEDED = 'ENS_BID_PLACE_SUCCEEDED',
  ENS_BID_PLACE_FAILED = 'ENS_BID_PLACE_FAILED'
}
