export enum TypeKeys {
  CURRENT_TIME_BOUNTY_SET = 'CURRENT_TIME_BOUNTY_SET',
  CURRENT_WINDOW_SIZE_SET = 'CURRENT_WINDOW_SIZE_SET',
  CURRENT_WINDOW_START_SET = 'CURRENT_WINDOW_START_SET',
  CURRENT_SCHEDULE_TIMESTAMP_SET = 'CURRENT_SCHEDULE_TIMESTAMP_SET',
  CURRENT_SCHEDULE_TIMEZONE_SET = 'CURRENT_SCHEDULE_TIMEZONE_SET',
  CURRENT_SCHEDULE_TYPE = 'CURRENT_SCHEDULE_TYPE',
  CURRENT_SCHEDULING_TOGGLE = 'CURRENT_SCHEDULING_TOGGLE',

  TIME_BOUNTY_FIELD_SET = 'TIME_BOUNTY_FIELD_SET',
  WINDOW_SIZE_FIELD_SET = 'WINDOW_SIZE_FIELD_SET',
  WINDOW_START_FIELD_SET = 'WINDOW_START_FIELD_SET',
  SCHEDULE_GAS_PRICE_FIELD_SET = 'SCHEDULE_GAS_PRICE_SET',
  SCHEDULE_GAS_LIMIT_FIELD_SET = 'SCHEDULE_GAS_LIMIT_SET',
  SCHEDULE_TIMESTAMP_FIELD_SET = 'SCHEDULE_TIMESTAMP_FIELD_SET',
  SCHEDULE_TIMEZONE_SET = 'SCHEDULE_TIMEZONE_SET',
  SCHEDULE_TYPE_SET = 'SCHEDULE_TYPE_SET',
  SCHEDULING_TOGGLE_SET = 'SCHEDULING_TOGGLE_SET',
  SCHEDULE_DEPOSIT_FIELD_SET = 'SCHEDULE_DEPOSIT_FIELD_SET',
  SCHEDULE_PARAMS_VALIDITY_SET = 'SCHEDULE_PARAMS_VALIDITY_SET'
}
