export enum TypeKeys {
  DATA_FIELD_SET = 'DATA_FIELD_SET',
  GAS_LIMIT_FIELD_SET = 'GAS_LIMIT_FIELD_SET',
  ADDRESS_FIELD_SET = 'ADDRESS_FIELD_SET',
  AMOUNT_FIELD_SET = 'AMOUNT_FIELD_SET',
  NONCE_FIELD_SET = 'NONCE_FIELD_SET',
  CLEAR_FIELDS = 'CLEAR_FIELDS'
}
