export enum WalletId {
  WEB3 = 'WEB3',
  METAMASK = 'METAMASK',
  TRUST = 'TRUST',
  FRAME = 'FRAME',
  COINBASE = 'COINBASE',
  LEDGER_NANO_S = 'LEDGER_NANO_S',
  TREZOR = 'TREZOR',
  KEYSTORE_FILE = 'KEYSTORE_FILE',
  PRIVATE_KEY = 'PRIVATE_KEY',
  MNEMONIC_PHRASE = 'MNEMONIC_PHRASE',
  VIEW_ONLY = 'VIEW_ONLY',
  WALLETCONNECT = 'WALLETCONNECT',

  LEDGER_NANO_S_NEW = 'LEDGER_NANO_S_NEW',
  TREZOR_NEW = 'TREZOR_NEW',
  MNEMONIC_PHRASE_NEW = 'MNEMONIC_PHRASE_NEW'
}
