export enum TypeKeys {
  GENERATE_WALLET_GENERATE_WALLET = 'GENERATE_WALLET_GENERATE_WALLET',
  GENERATE_WALLET_CONTINUE_TO_PAPER = 'GENERATE_WALLET_CONTINUE_TO_PAPER',
  GENERATE_WALLET_RESET = 'GENERATE_WALLET_RESET'
}
