export enum TAB {
  VIEW = 'NAV_VIEW',
  CREATE = 'NAV_GENERATEWALLET',
  SWAP = 'NAV_SWAP',
  CONTRACTS = 'NAV_CONTRACTS',
  ENS = 'NAV_ENS',
  SIGN = 'NAV_SIGN',
  TXSTATUS = 'NAV_TXSTATUS',
  BROADCAST = 'NAV_BROADCAST'
}
