export enum TypeKeys {
  WALLET_UNLOCK_PRIVATE_KEY = 'WALLET_UNLOCK_PRIVATE_KEY',
  WALLET_UNLOCK_KEYSTORE = 'WALLET_UNLOCK_KEYSTORE',
  WALLET_UNLOCK_MNEMONIC = 'WALLET_UNLOCK_MNEMONIC',
  WALLET_UNLOCK_WEB3 = 'WALLET_UNLOCK_WEB3',
  WALLET_SET = 'WALLET_SET',
  WALLET_SET_BALANCE = 'WALLET_SET_BALANCE',
  WALLET_SET_TOKEN_BALANCES = 'WALLET_SET_TOKEN_BALANCES',
  WALLET_BROADCAST_TX_REQUESTED = 'WALLET_BROADCAST_TX_REQUESTED',
  WALLET_BROADCAST_TX_FAILED = 'WALLET_BROADCAST_TX_FAILED',
  WALLET_BROADCAST_TX_SUCCEEDED = 'WALLET_BROADCAST_TX_SUCCEEDED',
  WALLET_RESET = 'WALLET_RESET'
}
