export enum TypeKeys {
  WALLET_UNLOCK_PRIVATE_KEY = 'WALLET_UNLOCK_PRIVATE_KEY',
  WALLET_UNLOCK_KEYSTORE = 'WALLET_UNLOCK_KEYSTORE',
  WALLET_UNLOCK_MNEMONIC = 'WALLET_UNLOCK_MNEMONIC',
  WALLET_UNLOCK_WEB3 = 'WALLET_UNLOCK_WEB3',
  WALLET_SET = 'WALLET_SET',
  WALLET_SET_BALANCE_PENDING = 'WALLET_SET_BALANCE_PENDING',
  WALLET_SET_BALANCE_FULFILLED = 'WALLET_SET_BALANCE_FULFILLED',
  WALLET_SET_BALANCE_REJECTED = 'WALLET_SET_BALANCE_REJECTED',
  WALLET_SET_TOKEN_BALANCES_PENDING = 'WALLET_SET_TOKEN_BALANCES_PENDING',
  WALLET_SET_TOKEN_BALANCES_FULFILLED = 'WALLET_SET_TOKEN_BALANCES_FULFILLED',
  WALLET_SET_TOKEN_BALANCES_REJECTED = 'WALLET_SET_TOKEN_BALANCES_REJECTED',
  WALLET_RESET = 'WALLET_RESET'
}
