export const NODE_CHANGE = 'CONFIG_NODE_CHANGE';
export const LANGUAGE_CHANGE = 'CONFIG_LANGUAGE_CHANGE';
export const GAS_PRICE_CHANGE = 'CONFIG_GAS_PRICE';

export default {
  NODE_CHANGE,
  LANGUAGE_CHANGE,
  GAS_PRICE_CHANGE
};
