export const FETCH_NODE_CONTRACTS = 'CONTRACTS_FETCH_NODE_CONTRACTS';
export const SET_NODE_CONTRACTS = 'CONTRACTS_SET_NODE_CONTRACTS';
export const ACCESS_CONTRACT = 'CONTRACTS_ACCESS_CONTRACT';
export const SET_INTERACTIVE_CONTRACT = 'CONTRACTS_SET_INTERACTIVE_CONTRACT';

export default {
  FETCH_NODE_CONTRACTS,
  SET_NODE_CONTRACTS,
  ACCESS_CONTRACT,
  SET_INTERACTIVE_CONTRACT
};
