export const GENERATE_WALLET_SHOW_PASSWORD = 'GENERATE_WALLET_SHOW_PASSWORD';
export const GENERATE_WALLET_FILE = 'GENERATE_WALLET_FILE';
export const GENERATE_WALLET_HAS_DOWNLOADED_FILE =
  'GENERATE_WALLET_HAS_DOWNLOADED_FILE';
export const GENERATE_WALLET_CONTINUE_TO_PAPER =
  'GENERATE_WALLET_CONTINUE_TO_PAPER';
