export const GENERATE_WALLET_SHOW_PASSWORD = 'GENERATE_WALLET_SHOW_PASSWORD';
export const GENERATE_WALLET_FILE = 'GENERATE_WALLET_FILE'
export const GENERATE_WALLET_HAS_DOWNLOADED_FILE = 'GENERATE_WALLET_HAS_DOWNLOADED_FILE'
export const GENERATE_WALLET_CONTINUE_TO_PAPER = 'GENERATE_WALLET_CONTINUE_TO_PAPER'


export const SHOW_GENERATE_WALLET_PASSWORD_ACTION = () => Object ({
    type: GENERATE_WALLET_SHOW_PASSWORD
})

export const GENERATE_WALLET_FILE_ACTION = () => Object ({
    type: GENERATE_WALLET_FILE
})

export const GENERATE_WALLET_HAS_DOWNLOADED_FILE_ACTION = () => Object ({
    type: GENERATE_WALLET_HAS_DOWNLOADED_FILE
})

export const GENERATE_WALLET_CONTINUE_TO_PAPER_ACTION = () => Object ({
    type: GENERATE_WALLET_CONTINUE_TO_PAPER
})
