export const GENERATE_WALLET_SHOW_PASSWORD = 'GENERATE_WALLET_SHOW_PASSWORD';
export const GENERATE_WALLET_FILE = 'GENERATE_WALLET_FILE';
export const GENERATE_WALLET_DOWNLOAD_FILE = 'GENERATE_WALLET_DOWNLOAD_FILE';
export const GENERATE_WALLET_CONFIRM_CONTINUE_TO_PAPER =
  'GENERATE_WALLET_CONFIRM_CONTINUE_TO_PAPER';
export const RESET_GENERATE_WALLET = 'RESET_GENERATE_WALLET';
