export const GENERATE_WALLET_SHOW_PASSWORD = 'GENERATE_WALLET_SHOW_PASSWORD';
export const GENERATE_WALLET_FILE = 'GENERATE_WALLET_FILE'
export const GENERATE_WALLET_FILE_CONFIRM = 'GENERATE_WALLET_FILE_CONFIRM'


export const SHOW_GENERATE_WALLET_PASSWORD_ACTION = () => Object ({
    type: GENERATE_WALLET_SHOW_PASSWORD
})

export const GENERATE_WALLET_FILE_ACTION = () => Object ({
    type: GENERATE_WALLET_FILE
})


