export enum TypeKeys {
  CONFIG_LANGUAGE_CHANGE = 'CONFIG_LANGUAGE_CHANGE',
  CONFIG_NODE_CHANGE = 'CONFIG_NODE_CHANGE',
  CONFIG_NODE_CHANGE_INTENT = 'CONFIG_NODE_CHANGE_INTENT',
  CONFIG_GAS_PRICE = 'CONFIG_GAS_PRICE',
  CONFIG_TOGGLE_OFFLINE = 'CONFIG_TOGGLE_OFFLINE',
  CONFIG_FORCE_OFFLINE = 'CONFIG_FORCE_OFFLINE',
  CONFIG_POLL_OFFLINE_STATUS = 'CONFIG_POLL_OFFLINE_STATUS',
  CONFIG_ADD_CUSTOM_NODE = 'CONFIG_ADD_CUSTOM_NODE',
  CONFIG_REMOVE_CUSTOM_NODE = 'CONFIG_REMOVE_CUSTOM_NODE',
  CONFIG_SET_LATEST_BLOCK = 'CONFIG_SET_LATEST_BLOCK',
  CONFIG_NODE_WEB3_UNSET = 'CONFIG_NODE_WEB3_UNSET'
}
