export enum TypeKeys {
  ADD_ADDRESS_LABEL_REQUESTED = 'ADD_ADDRESS_LABEL_REQUESTED',
  ADD_ADDRESS_LABEL_SUCCEEDED = 'ADD_ADDRESS_LABEL_SUCCEEDED',
  ADD_ADDRESS_LABEL_FAILED = 'ADD_ADDRESS_LABEL_FAILED',
  REMOVE_ADDRESS_LABEL = 'REMOVE_ADDRESS_LABEL',
  d = 'd'
}
