# If someone with write access comments "/ok-to-test" on a pull request, emit a repository_dispatch event
name: Ok to test

on:
  issue_comment:
    types: [created]

jobs:
  ok-to-test:
    runs-on: ubuntu-latest
    steps:
      # Generate a GitHub App installation access token from an App ID and private key
      # To create a new GitHub App:
      #   https://developer.github.com/apps/building-github-apps/creating-a-github-app/
      # See app.yml for an example app manifest
      - name: Generate token
        id: generate_token
        uses: MyCryptoHQ/github-app-token@v1
        with:
          app_id: ${{ secrets.WORKFLOW_APP_ID }}
          private_key: ${{ secrets.WORKFLOW_PRIVATE_KEY }}

      - name: Slash Command Dispatch
        uses: peter-evans/slash-command-dispatch@v1
        env:
          TOKEN: ${{ steps.generate_token.outputs.token }}
        with:
          token: ${{ env.TOKEN }} # GitHub App installation access token
          # token: ${{ secrets.PERSONAL_ACCESS_TOKEN }} # PAT or OAuth token will also work
          reaction-token: ${{ secrets.GITHUB_TOKEN }}
          issue-type: pull-request
          commands: ok-to-test
          named-args: true
          permission: write
